### ISSUE TITLE
Possible bug retrieving JavaDoc JARs

### ISSUE THREAD

**Issue by keilw** [maxcellent/javadoc.io#62] opened 2020-11-26 13:55 UTC
There could be a bug retrieving JavaDoc JARs, because the javadoc-jar versions 2.1
https://repo1.maven.org/maven2/javax/measure/unit-api/2.1/
and 2.11
https://repo1.maven.org/maven2/javax/measure/unit-api/2.1.1/
of https://javadoc.io/doc/javax.measure/unit-api, because it constantly falls back to the outdated 2.0-PRD although the list of versions does show 2.0, 2.1 and 2.1.1 but it won't allow to view them.

**Comment by keilw** [comment] 2020-12-02 14:35
It worked for the RI https://www.javadoc.io/doc/tech.units/indriya/latest/overview-summary.html of that JSR but still fails for the API which does not show any version beyond 2.0-PRD.

**Comment by maxcellent** [comment] 2020-12-03 02:10
This is because the published jar is empty. You can check by yourself. Simply download and unzip https://repo1.maven.org/maven2/javax/measure/unit-api/2.1/unit-api-2.1-javadoc.jar 

Because javadoc.io is not able to locate index.html it will automatically fallback to a previous valid version. 

This is an expected behavior. I am closing it for now. Feel free to reopen if you have more concerns.

**Closed as completed by maxcellent** 2020-12-03 02:10 UTC

**Comment by keilw** [comment] 2020-12-03 09:50
That's quite bizarre because MavenCentral had no isssues with the file. Thanks for pointing it out, we have our own JavaDoc URL https://unitsofmeasurement.github.io/unit-api/site/apidocs/index.html, but we may publish a new version of the API when a need arises.

**Comment by maxcellent** [comment] 2020-12-03 14:26
Maven central should really verify the `javadoc.jar` but unfortunately they don't...

**Comment by keilw** [comment] 2020-12-03 14:36
It really looks like a bug in the maven-javadoc plugin probably from a particular Java version. Locally I can override that by forcing the `JAVA_HOME` to use Java 8, then it works. In the "snapshot" repo I can see, that it stopped working in the container around July 2020, I can't say for sure, but either the plugin version or a different JVM cause it. Will create an issue in the API project to find a more sustainable solution that works also on the CI servers.
