### ISSUE TITLE
spring-cloud-stream stopped appearing at version 3.x

### ISSUE THREAD

**Issue by dsyer** [maxcellent/javadoc.io#36] opened 2020-02-06 15:34 UTC
3.0.1 is clearly in Maven Central (https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-stream/3.0.1.RELEASE/), but it never showed up in javadoc.io (https://www.javadoc.io/doc/org.springframework.cloud/spring-cloud-stream/3.0.1.RELEASE/index.html).

**Comment by maxcellent** [comment] 2020-02-07 09:44
This is because the `spring-cloud-stream-3.0.1.RELEASE-javadoc.jar` doesn't have an `index.html` under the root folder. Can you tell me how you are generating `javadoc.jar`?

**Comment by olegz** [comment] 2020-02-10 18:17
We're working on fixing it, will let you know

**Comment by olegz** [comment] 2020-02-12 15:15
SO we fixed the stream and I can confirm now that the  javadoc JAR file does indeed contains index.html. So it will be available when we cut 3.0.2.RELEASE.

**Comment by maxcellent** [comment] 2020-02-13 04:38
> SO we fixed the stream and I can confirm now that the javadoc JAR file does indeed contains index.html. So it will be available when we cut 3.0.2.RELEASE.

cool. I am closing the issue now. Feel free to reopen if it still doesn't work.

**Closed as completed by maxcellent** 2020-02-13 04:38 UTC
