### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by NicolasMassart** [maxcellent/javadoc.io#72] opened 2021-04-02 10:14 UTC
Javadoc.io is down and Cloudflare returns a 521 error.
<img width="400" alt="Screenshot 2021-04-02 at 12 13 54" src="https://user-images.githubusercontent.com/4677568/113407124-022c1200-93ad-11eb-9a3b-fd5593e08add.png">

**Comment by maxcellent** [comment] 2021-04-02 14:13
not expected and never happened before. I have restarted the service. Will investigate and keep this ticket up to date.

**Comment by maxcellent** [comment] 2021-04-02 16:17
There was a slowness in AWS which is causing thousands of connections reading data at the same time. 

Because of the way Java SSL works, it seems each connection creates their own SSLEngine, which takes about 200KB heap space each. 

I have capped number of connections for now. Will keep an eye in the next few days.

**Comment by trustin** [comment] 2021-04-05 06:24
How about re-opening this ticket or creating an announcement/status update issue so people know this is ongoing?

**Comment by trustin** [comment] 2021-04-05 08:38
Last but not least, I'd like to appreciate your contribution to the whole Java community by hosting and maintaining javadoc.io. It's indispensable tool for today's open source Java developers! You might want to add a list of contributions and donations you're looking for to the front page, so people can consider helping you in some way. :bulb:

**Comment by maxcellent** [comment] 2021-04-05 09:51
The root cause is a daily batch job which is trying to load 39.5m rows into memory. It's not implemented in scalable way on day one because at that time it's only a few hundred rows returned by the same query.

This is now fixed, tested and deployed.

I have also setup an uptime alert to make sure anything similar will be captured asap.

**Closed as completed by maxcellent** 2021-04-05 09:51 UTC

**Comment by maxcellent** [comment] 2021-04-05 10:11
> Last but not least, I'd like to appreciate your contribution to the whole Java community by hosting and maintaining javadoc.io. It's indispensable tool for today's open source Java developers! You might want to add a list of contributions and donations you're looking for to the front page, so people can consider helping you in some way. 💡

Thanks Trustin, as a heavy Netty user myself, your encouragement means a lot to me. 

Yes I've been thinking about it seriously. The only concern of receiving money is the compliance department of the company I am working for. 

It's still good to know that ppl are interested to financially support the project. I will be more determined to go through the process!

**Comment by trustin** [comment] 2021-04-05 10:12
Thank you for fixing this problem, @maxcellent!
